-- Copy and paste this into your Supabase SQL Editor to create the missing table

-- 1. Create the suggest_resources table
CREATE TABLE IF NOT EXISTS public.suggest_resources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    title TEXT NOT NULL,
    author TEXT,
    note TEXT
);

-- 2. Enable Row Level Security (RLS) is best practice
ALTER TABLE public.suggest_resources ENABLE ROW LEVEL SECURITY;

-- 3. Create a policy to allow anyone (even guests) to submit suggestions
-- We interpret 'anon' as guest users and 'authenticated' as logged-in users.
CREATE POLICY "Allow public inserts" 
ON public.suggest_resources 
FOR INSERT 
TO anon, authenticated 
WITH CHECK (true);

-- 4. Verify the table is accessible
GRANT ALL ON public.suggest_resources TO anon, authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.suggest_resources_id_seq TO anon, authenticated;
